subprojects {
    apply plugin: 'java-library'

    version = mod_version
    group = mod_group_id

    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation platform("org.junit:junit-bom:${junit_version}")
        testImplementation 'org.junit.jupiter:junit-jupiter'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.named('test', Test) {
        useJUnitPlatform()
    }
}
